CREATE TABLE Turno (
    TurnoID INT IDENTITY(1,1) PRIMARY KEY,
    PacienteID INT NOT NULL,
    MedicoID INT NOT NULL,
    FechaHora DATETIME NOT NULL,
    
    FOREIGN KEY (PacienteID) REFERENCES Paciente(Id),
    FOREIGN KEY (MedicoID) REFERENCES Medico(Id)
);


INSERT INTO Turno (PacienteID, MedicoID, FechaHora)
VALUES 
    (1, 3, DATEADD(HOUR, RAND() * 24, DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 30), GETDATE()))),
    (2, 1, DATEADD(HOUR, RAND() * 24, DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 30), GETDATE()))),
    (3, 1, DATEADD(HOUR, RAND() * 24, DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 30), GETDATE()))),
    (4, 2, DATEADD(HOUR, RAND() * 24, DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 30), GETDATE()))),
    (3, 3, DATEADD(HOUR, RAND() * 24, DATEADD(DAY, ABS(CHECKSUM(NEWID()) % 30), GETDATE())));


